### ISSUE TITLE
Empty barrels of beer

### ISSUE THREAD

**Issue by becousae** [ZeusWPI/Saruman#55]
All items are picked up, and what's left of them is brought back.

Beer barrels are brought back empty though.
Would it be useful to create a special item for this, that is displayed in the table, but partners can't make reservations for? We would have to link them somehow though, to keep the stock up to date.

**Comment by TomNaessens** [comment]
Implemented, but differently as described: 

- Deposit was added to an item
- Returning an item can be done in 2 different ways now:
   - used: empty (e.g. an empty keg), implications on billing: users pay for the item, but get their deposit back
   - unused (e.g. a full keg), implications on billing: users get both payment and deposit back
